### ISSUE TITLE
Add `--multisig` Flag to Ping Command to Verify Multisig Support

### ISSUE THREAD

**Issue by MatusKysel** [bloxapp/ssv-dkg#128]
### Background

Some operators may be misconfigured or not connected to Ethereum 1.0 (eth1), which is necessary for multisig functionality. We need a way to identify operators that support multisig.

### Task

- **Enhance Ping Command:**
  - Add a `--multisig` flag to the `ping` command.
  - When this flag is used, the `ping` command should fail if the operator is not connected to eth1.

- **Update Health Check:**
  - Modify the health check to verify multisig support on all operators.

### Acceptance Criteria

- The `ping` command with `--multisig`:
  - Succeeds only if the operator is connected to eth1.
  - Fails with a clear error message if not connected.

- Health check reports accurately reflect multisig support status.
- Documentation is updated to include the new `--multisig` flag.

---

By implementing this, we can ensure that we only use operators that support multisig and are properly connected to eth1.

**Comment by pavelkrolevets** [comment]
IMO we dont even need a flag to `ping`. We just get new `pong` message with fields indicating that its multisig + connected. 
In this case if we ping old operators we got a message that they online but multisig not supported.
