### ISSUE TITLE
Fix generate output 

### ISSUE THREAD

**Issue by MatusKysel** [bloxapp/ssv-dkg#140]
new functions `generate-resign-msg` and `generate-reshare-msg` are encoding output strange way

```json
"Fork":[0,0,0,0],"WithdrawalCredentials":"gVksPeGEo+LA3LWiYbwQe/qR9JQ=","Owner":[220,200,70,250,16,199,207,206,158,110,179,126,6,237,147,182,102,207,197,233],"Nonce":10},"Proofs":[{
```

everything needs to be matching output that we already used for deposit file, keyshares, proofs ...

**Comment by pavelkrolevets** [comment]
fixed here https://github.com/ssvlabs/ssv-dkg/pull/141
