### ISSUE TITLE
Complete fix of 5.4 Reshare Denial-of-Service via Predicable Instance IDs

### ISSUE THREAD

**Issue by MatusKysel** [bloxapp/ssv-dkg#161]
5.4 I think we could split ID into following `ID[24]byte=[8]byte(initiator pubkey hash) + [8]byte(message hash) + [8]byte(random entropy)` and as the initiator is signing all the msgs, no one else can produce msg with following ID as msg signature would be produce by different key

**Comment by pavelkrolevets** [comment]
https://github.com/ssvlabs/ssv-dkg/pull/162
